openapi: 3.0.3
info:
  version: 5.13.0
  title: Pinterest User API
  description: This is the description of your API.
  contact:
    name: Pinterest, Inc.
    url: https://developers.pinterest.com/
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://developers.pinterest.com/terms/
servers:
- url: https://api.pinterest.com/v5
tags:
- name: User
paths:
  /user_account:
    get:
      summary: Get user account
      description: 'Get account information for the "operation user_account"

        - By default, the "operation user_account" is the token user_account.


        If using Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account". See <a href=''/docs/reference/business-access/''>Understanding Business Access</a> for more information.'
      tags:
      - User
      operationId: user_account/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
  /user_account/analytics:
    get:
      summary: Get user account analytics
      description: 'Get analytics for the "operation user_account"

        - By default, the "operation user_account" is the token user_account.


        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".'
      tags:
      - User
      operationId: user_account/analytics
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_analytics
      x-sandbox: disabled
  /user_account/analytics/top_pins:
    get:
      summary: Get user account top pins analytics
      description: 'Gets analytics data about a user''s top pins (limited to the top 50).

        - By default, the "operation user_account" is the token user_account.


        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".'
      tags:
      - User
      operationId: user_account/analytics/top_pins
      security:
      - pinterest_oauth2:
        - pins:read
        - user_accounts:read
      x-ratelimit-category: org_analytics
      x-sandbox: disabled
  /user_account/analytics/top_video_pins:
    get:
      summary: Get user account top video pins analytics
      description: 'Gets analytics data about a user''s top video pins (limited to the top 50).

        - By default, the "operation user_account" is the token user_account.


        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".'
      tags:
      - User
      operationId: user_account/analytics/top_video_pins
      security:
      - pinterest_oauth2:
        - pins:read
        - user_accounts:read
      x-ratelimit-category: org_analytics
      x-sandbox: disabled
  /user_account/businesses:
    get:
      summary: List linked businesses
      description: Get a list of your linked business accounts.
      operationId: linked_business_accounts/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
      tags:
      - User
  /user_account/followers:
    get:
      summary: List followers
      description: Get a list of your followers.
      operationId: followers/list
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - User
  /user_account/following:
    get:
      summary: List following
      description: Get a list of who a certain user follows.
      operationId: user_following/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: disabled
      tags:
      - User
  /user_account/following/boards:
    get:
      summary: List following boards
      description: Get a list of the boards a user follows. The request returns a board summary object array.
      operationId: boards_user_follows/list
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
      tags:
      - User
  /user_account/following/{username}:
    post:
      summary: Follow user
      description: '<strong>This endpoint is currently in beta and not available to all apps. <a href=''/docs/new/about-beta-access/''>Learn more</a>.</strong>


        Use this request, as a signed-in user, to follow another user.'
      tags:
      - User
      operationId: follow_user/update
      security:
      - pinterest_oauth2:
        - user_accounts:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /user_account/websites:
    post:
      summary: Verify website
      description: Verify a website as a signed-in user.
      tags:
      - User
      operationId: verify_website/update
      security:
      - pinterest_oauth2:
        - user_accounts:write
      x-ratelimit-category: org_write
      x-sandbox: disabled
    get:
      summary: Get user websites
      description: Get user websites, claimed or not
      tags:
      - User
      operationId: user_websites/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: disabled
    delete:
      summary: Unverify website
      description: Unverifu a website verified by the signed-in user.
      tags:
      - User
      operationId: unverify_website/delete
      security:
      - pinterest_oauth2:
        - user_accounts:write
      x-ratelimit-category: org_write
      x-sandbox: disabled
  /user_account/websites/verification:
    get:
      summary: Get user verification code for website claiming
      description: Get verification code for user to install on the website to claim it.
      tags:
      - User
      operationId: website_verification/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: disabled
components:
  securitySchemes:
    pinterest_oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.pinterest.com/oauth/
          tokenUrl: https://api.pinterest.com/v5/oauth/token
          scopes:
            ads:read: See all of your advertising data, including ads, ad groups, campaigns etc.
            ads:write: Create, update, or delete ads, ad groups, campaigns etc.
            billing:read: See all of your billing data, billing profile, etc.
            billing:write: Create, update, or delete billing data, billing profiles, etc.
            biz_access:read: See business access data
            biz_access:write: Create, update, or delete business access data
            boards:read: See your public boards, including group boards you join
            boards:read_secret: See your secret boards
            boards:write: Create, update, or delete your public boards
            boards:write_secret: Create, update, or delete your secret boards
            catalogs:read: See all of your catalogs data
            catalogs:write: Create, update, or delete your catalogs data
            pins:read: See your public Pins
            pins:read_secret: See your secret Pins
            pins:write: Create, update, or delete your public Pins
            pins:write_secret: Create, update, or delete your secret Pins
            user_accounts:read: See your user accounts and followers
            user_accounts:write: Update your user accounts and followers
    conversion_token:
      type: http
      scheme: bearer
      description: This security scheme only applies to the conversion events endpoint (POST /ad_accounts/{ad_account_id}/events). This endpoint requires a bearer token generated via Ads Manager (ads.pinterest.com).
    basic:
      type: http
      scheme: basic
x-tagGroups:
- name: Pin and Boards
  tags:
  - pins
  - boards
  - media
  - aggregated_comments
  - aggregated_pin_data
  - user_account
- name: Campaign Management
  tags:
  - ad_accounts
  - campaigns
  - ad_groups
  - ads
  - product_group_promotions
  - bulk
- name: Targeting
  tags:
  - audiences
  - customer_lists
  - keywords
  - targeting_template
  - audience_insights
  - audience_sharing
- name: Ad Formats
  tags:
  - lead_forms
  - lead_ads
  - leads_export
- name: Billing
  tags:
  - billing
  - order_lines
  - terms_of_service
- name: Business Access
  tags:
  - business_access_assets
  - business_access_invite
  - business_access_relationships
- name: Conversions
  tags:
  - conversion_events
  - conversion_tags
- name: Others
  tags:
  - integrations
  - oauth
  - resources
  - search
  - terms
- name: Shopping
  tags:
  - catalogs
- name: Deprecated
  tags:
  - product_groups
