openapi: 3.2.0
info:
  version: 5.13.0
  title: Pinterest Pins API
  description: This is the description of your API.
  contact:
    name: Pinterest, Inc.
    url: https://developers.pinterest.com/
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://developers.pinterest.com/terms/
servers:
- url: https://api.pinterest.com/v5
tags:
- name: Pins
paths:
  /pins:
    get:
      summary: List Pins
      description: 'Get a list of the Pins owned by the "operation user_account".

        - By default, the "operation user_account" is the token user_account.

        - All Pins owned by the "operation user_account" are included, regardless of who owns the board they are on.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".


        Disclaimer: there are known performance issues when filtering by field creative_type and including protected pins. If your

        request is timing out in this scenario we encourage you to use GET List Pins on Board.'
      operationId: pins/list
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
      tags:
      - Pins
    post:
      summary: Create Pin
      description: 'Create a Pin on a board or board section owned by the "operation user_account".


        Note: If the current "operation user_account" (defined by the access token) has access to another user''s Ad Accounts via Pinterest Business Access, you can modify your request to make use of the current operation_user_account''s permissions to those Ad Accounts by including the ad_account_id in the path parameters for the request (e.g. .../?ad_account_id=12345&...).


        - This function is intended solely for publishing new content created by the user. If you are interested in saving content created by others to your Pinterest boards, sometimes called ''curated content'', please use our Save button instead. For more tips on creating fresh content for Pinterest, review our Content App Solutions Guide.


        Learn more about video Pin creation.'
      tags:
      - Pins
      operationId: pins/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /pins/{pin_id}:
    get:
      summary: Get Pin
      description: 'Get a Pin owned by the "operation user_account" - or on a group board that has been shared with this account.

        - By default, the "operation user_account" is the token user_account.


        Optional: Business Access: Specify an ad_account_id (obtained via List ad accounts) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following Business Access roles on the ad_account:


        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.

        - For Pins on secret boards: Owner, Admin.'
      tags:
      - Pins
      operationId: pins/get
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
    delete:
      summary: Delete Pin
      description: 'Delete a Pins owned by the "operation user_account" - or on a group board that has been shared with this account.

        - By default, the "operation user_account" is the token user_account.


        Optional: Business Access: Specify an ad_account_id (obtained via List ad accounts) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following Business Access roles on the ad_account:


        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.

        - For Pins on secret boards: Owner, Admin.'
      tags:
      - Pins
      operationId: pins/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
    patch:
      summary: Update Pin
      description: 'Update a pin owned by the "operating user_account".

        - By default, the "operation user_account" is the token user_account.


        Optional: Business Access: Specify an ad_account_id (obtained via List ad accounts) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following Business Access roles on the ad_account:


        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.

        - For Pins on secret boards: Owner, Admin.


        This endpoint is currently in beta and not available to all apps. Learn more.'
      tags:
      - Pins
      operationId: pins/update
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /pins/{pin_id}/analytics:
    get:
      summary: Get Pin analytics
      description: 'Get analytics for a Pin owned by the "operation user_account" - or on a group board that has been shared with this account.

        - By default, the "operation user_account" is the token user_account.


        Optional: Business Access: Specify an ad_account_id (obtained via List ad accounts) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following Business Access roles on the ad_account:


        - For Pins on public or protected boards: Admin, Analyst.

        - For Pins on secret boards: Admin.


        If Pin was created before 2023-03-20 lifetime metrics will only be available for Video and Idea Pin formats. Lifetime metrics are available for all Pin formats since then.'
      tags:
      - Pins
      operationId: pins/analytics
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_analytics
      x-sandbox: disabled
  /pins/analytics:
    get:
      summary: Get multiple Pin analytics
      description: 'This endpoint is currently in beta and not available to all apps. Learn more.


        Get analytics for multiple pins owned by the "operation user_account" - or on a group board that has been shared with this account.

        - The maximum number of pins supported in a single request is 100.

        - By default, the "operation user_account" is the token user_account.


        Optional: Business Access: Specify an ad_account_id (obtained via List ad accounts) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following Business Access roles on the ad_account:


        - For Pins on public or protected boards: Admin, Analyst.

        - For Pins on secret boards: Admin.


        If Pin was created before 2023-03-20 lifetime metrics will only be available for Video and Idea Pin formats. Lifetime metrics are available for all Pin formats since then.'
      tags:
      - Pins
      operationId: multi_pins/analytics
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_analytics
      x-sandbox: disabled
  /pins/{pin_id}/save:
    post:
      summary: Save Pin
      description: 'Save a Pin on a board or board section owned by the "operation user_account".

        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an ad_account_id (obtained via List ad accounts) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following Business Access roles on the ad_account:


        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.

        - For Pins on secret boards: Owner, Admin.


        - Any Pin type can be saved: image Pin, video Pin, Idea Pin, product Pin, etc.

        - Any public Pin can be saved given a pin ID.'
      tags:
      - Pins
      operationId: pins/save
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
components:
  securitySchemes:
    pinterest_oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.pinterest.com/oauth/
          tokenUrl: https://api.pinterest.com/v5/oauth/token
          scopes:
            ads:read: See all of your advertising data, including ads, ad groups, campaigns etc.
            ads:write: Create, update, or delete ads, ad groups, campaigns etc.
            billing:read: See all of your billing data, billing profile, etc.
            billing:write: Create, update, or delete billing data, billing profiles, etc.
            biz_access:read: See business access data
            biz_access:write: Create, update, or delete business access data
            boards:read: See your public boards, including group boards you join
            boards:read_secret: See your secret boards
            boards:write: Create, update, or delete your public boards
            boards:write_secret: Create, update, or delete your secret boards
            catalogs:read: See all of your catalogs data
            catalogs:write: Create, update, or delete your catalogs data
            pins:read: See your public Pins
            pins:read_secret: See your secret Pins
            pins:write: Create, update, or delete your public Pins
            pins:write_secret: Create, update, or delete your secret Pins
            user_accounts:read: See your user accounts and followers
            user_accounts:write: Update your user accounts and followers
    conversion_token:
      type: http
      scheme: bearer
      description: This security scheme only applies to the conversion events endpoint (POST /ad_accounts/{ad_account_id}/events). This endpoint requires a bearer token generated via Ads Manager (ads.pinterest.com).
    basic:
      type: http
      scheme: basic
x-tagGroups:
- name: Pin and Boards
  tags:
  - pins
  - boards
  - media
  - aggregated_comments
  - aggregated_pin_data
  - user_account
- name: Campaign Management
  tags:
  - ad_accounts
  - campaigns
  - ad_groups
  - ads
  - product_group_promotions
  - bulk
- name: Targeting
  tags:
  - audiences
  - customer_lists
  - keywords
  - targeting_template
  - audience_insights
  - audience_sharing
- name: Ad Formats
  tags:
  - lead_forms
  - lead_ads
  - leads_export
- name: Billing
  tags:
  - billing
  - order_lines
  - terms_of_service
- name: Business Access
  tags:
  - business_access_assets
  - business_access_invite
  - business_access_relationships
- name: Conversions
  tags:
  - conversion_events
  - conversion_tags
- name: Others
  tags:
  - integrations
  - oauth
  - resources
  - search
  - terms
- name: Shopping
  tags:
  - catalogs
- name: Deprecated
  tags:
  - product_groups
