openapi: 3.0.3
info:
  version: 5.13.0
  title: Pinterest Board API
  description: This is the description of your API.
  contact:
    name: Pinterest, Inc.
    url: https://developers.pinterest.com/
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://developers.pinterest.com/terms/
servers:
- url: https://api.pinterest.com/v5
tags:
- name: Board
paths:
  /boards/{board_id}:
    get:
      summary: Get board
      description: 'Get a board owned by the operation user_account - or a group board that has been shared with this account.

        - Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".

        - By default, the "operation user_account" is the token user_account.'
      tags:
      - Board
      operationId: boards/get
      security:
      - pinterest_oauth2:
        - boards:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
    patch:
      summary: Update board
      description: 'Update a board owned by the "operating user_account".

        - Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".

        - By default, the "operation user_account" is the token user_account.'
      tags:
      - Board
      operationId: boards/update
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
    delete:
      summary: Delete board
      description: 'Delete a board owned by the "operation user_account".

        - Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".

        - By default, the "operation user_account" is the token user_account.'
      tags:
      - Board
      operationId: boards/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /boards/{board_id}/pins:
    get:
      summary: List Pins on board
      description: 'Get a list of the Pins on a board owned by the "operation user_account" - or on a group board that has been shared with this account.

        - Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".

        - By default, the "operation user_account" is the token user_account.'
      tags:
      - Board
      operationId: boards/list_pins
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
  /boards/{board_id}/sections:
    get:
      summary: List board sections
      description: 'Get a list of all board sections from a board owned by the "operation user_account" - or a group board that has been shared with this account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".

        - By default, the "operation user_account" is the token user_account.'
      tags:
      - Board
      operationId: board_sections/list
      security:
      - pinterest_oauth2:
        - boards:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
    post:
      summary: Create board section
      description: 'Create a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".

        - By default, the "operation user_account" is the token user_account.'
      tags:
      - Board
      operationId: board_sections/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /boards/{board_id}/sections/{section_id}:
    patch:
      summary: Update board section
      description: 'Update a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".

        - By default, the "operation user_account" is the token user_account.'
      tags:
      - Board
      operationId: board_sections/update
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
    delete:
      summary: Delete board section
      description: 'Delete a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".

        - By default, the "operation user_account" is the token user_account.'
      tags:
      - Board
      operationId: board_sections/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /boards/{board_id}/sections/{section_id}/pins:
    get:
      summary: List Pins on board section
      description: 'Get a list of the Pins on a board section of a board owned by the "operation user_account" - or on a group board that has been shared with this account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".

        - By default, the "operation user_account" is the token user_account.'
      tags:
      - Board
      operationId: board_sections/list_pins
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
components:
  securitySchemes:
    pinterest_oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.pinterest.com/oauth/
          tokenUrl: https://api.pinterest.com/v5/oauth/token
          scopes:
            ads:read: See all of your advertising data, including ads, ad groups, campaigns etc.
            ads:write: Create, update, or delete ads, ad groups, campaigns etc.
            billing:read: See all of your billing data, billing profile, etc.
            billing:write: Create, update, or delete billing data, billing profiles, etc.
            biz_access:read: See business access data
            biz_access:write: Create, update, or delete business access data
            boards:read: See your public boards, including group boards you join
            boards:read_secret: See your secret boards
            boards:write: Create, update, or delete your public boards
            boards:write_secret: Create, update, or delete your secret boards
            catalogs:read: See all of your catalogs data
            catalogs:write: Create, update, or delete your catalogs data
            pins:read: See your public Pins
            pins:read_secret: See your secret Pins
            pins:write: Create, update, or delete your public Pins
            pins:write_secret: Create, update, or delete your secret Pins
            user_accounts:read: See your user accounts and followers
            user_accounts:write: Update your user accounts and followers
    conversion_token:
      type: http
      scheme: bearer
      description: This security scheme only applies to the conversion events endpoint (POST /ad_accounts/{ad_account_id}/events). This endpoint requires a bearer token generated via Ads Manager (ads.pinterest.com).
    basic:
      type: http
      scheme: basic
x-tagGroups:
- name: Pin and Boards
  tags:
  - pins
  - boards
  - media
  - aggregated_comments
  - aggregated_pin_data
  - user_account
- name: Campaign Management
  tags:
  - ad_accounts
  - campaigns
  - ad_groups
  - ads
  - product_group_promotions
  - bulk
- name: Targeting
  tags:
  - audiences
  - customer_lists
  - keywords
  - targeting_template
  - audience_insights
  - audience_sharing
- name: Ad Formats
  tags:
  - lead_forms
  - lead_ads
  - leads_export
- name: Billing
  tags:
  - billing
  - order_lines
  - terms_of_service
- name: Business Access
  tags:
  - business_access_assets
  - business_access_invite
  - business_access_relationships
- name: Conversions
  tags:
  - conversion_events
  - conversion_tags
- name: Others
  tags:
  - integrations
  - oauth
  - resources
  - search
  - terms
- name: Shopping
  tags:
  - catalogs
- name: Deprecated
  tags:
  - product_groups
