openapi: 3.0.3
info:
  version: 5.13.0
  title: Pinterest Business API
  description: This is the description of your API.
  contact:
    name: Pinterest, Inc.
    url: https://developers.pinterest.com/
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://developers.pinterest.com/terms/
servers:
- url: https://api.pinterest.com/v5
tags:
- name: Business
paths:
  /businesses/{business_id}/assets/{asset_id}/members:
    get:
      summary: Get members with access to asset
      description: Get all the members the requesting business has granted access to on the given asset.
      operationId: business_asset_members/get
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Business
  /businesses/{business_id}/assets/{asset_id}/partners:
    get:
      summary: Get partners with access to asset
      description: 'Get all the partners the requesting business has granted access to on the given asset.

        Note: If the asset has been shared with you, an empty array will be returned. This is because an asset shared with

        you cannot be shared with a different partner.'
      operationId: business_asset_partners/get
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Business
  /businesses/{business_id}/invites/assets/access:
    post:
      summary: Update invite/request with an asset permission
      description: "Assign asset permissions information to an existing invite/request. Can be used to:\n- Request access to a partner's asset. Note: This is only for when no existing partnership exists. If an existing\n  partnership exists, use \"Create a request to access an existing partner's assets\" to request access to your\n  partner's assets.\n    - invite_type=\"PARTNER_REQUEST\"\n- Invite a partner to access your business assets. Note: This is only for when there is no existing partner[...]"
      operationId: create_asset_invites
      security:
      - pinterest_oauth2:
        - biz_access:read
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
  /businesses/{business_id}/requests/assets/access:
    post:
      summary: Create a request to access an existing partner's assets.
      description: Create a request to access an existing partner's assets with the specified permissions. The request will be sent to the partner for approval. The assets that can be requested are ad accounts and profiles.
      operationId: asset_access_requests/create
      security:
      - pinterest_oauth2:
        - biz_access:read
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
  /businesses/{business_id}/members:
    get:
      summary: Get business members
      description: 'Get all members of the specified business.

        The return response will include the member''s business_role and assets they have access to if assets_summary=TRUE'
      operationId: get/business_members
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Business
    patch:
      description: Update a member's business role within the business.
      summary: Update member's business role
      operationId: update/business_memberships
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
    delete:
      description: Terminate memberships between the specified members and your business.
      summary: Terminate business memberships
      operationId: delete_business_membership
      security:
      - pinterest_oauth2:
        - biz_access:read
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - Business
  /businesses/{business_id}/assets:
    get:
      summary: List business assets
      description: Get all the assets the requesting business has access to. This includes assets the business owns and assets the business has access to through partnerships.
      operationId: business_assets/get
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Business
  /businesses/{business_id}/members/{member_id}/assets:
    get:
      summary: Get assets assigned to a member
      description: 'Get assets on which you assigned asset permissions to the given member. Can be used to:

        - get all assets, regardless of asset type or

        - get assets of one asset type by using the asset_type query.

        The return response will include the permissions the member has to that asset and the asset type.'
      operationId: business_member_assets/get
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Business
  /businesses/{business_id}/members/assets/access:
    patch:
      description: 'Grant multiple members access to assets and/or update multiple member''s exisiting permissions to an asset.

        Note: Not all listed permissions are applicable to each asset type. For example, PROFILE_PUBLISHER would not be applicable to an asset of type AD_ACCOUNT. The permission level PROFILE_PUBLISHER is only available to an asset of the type PROFILE.

        '
      summary: Assign/Update member asset permissions
      operationId: business_members_asset_access/update
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
    delete:
      description: Terminate multiple members' access to an asset.
      summary: Delete member access to asset
      operationId: business_members_asset_access/delete
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
  /businesses/{business_id}/invites:
    get:
      summary: Get invites/requests
      description: Get the membership/partnership invites and/or requests for the authorized user.
      operationId: get/invites
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Business
    post:
      summary: Create invites or requests
      description: "Create batch invites or requests. Can create batch invites or requests as described below.\n- Invite members to join the business. This would required specifying the following:\n    - invite_type=\"MEMBER_INVITE\"\n    - business_role=\"EMPLOYEE\" OR business_role=\"BIZ_ADMIN\" (To learn more about business roles, visit\n    https://help.pinterest.com/en/business/article/profile-permissions-in-business-access.)\n    - members\n- Invite partners to access your business assets.[...]"
      operationId: create_membership_or_partnership_invites
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
    delete:
      summary: Cancel invites/requests
      description: Cancel membership/partnership invites and/or requests.
      operationId: cancel_invites_or_requests
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
  /businesses/{business_id}/partners/assets:
    patch:
      summary: Assign/Update partner asset permissions
      description: 'Grant multiple partners access to assets and/or update multiple partner''s exisiting permissions to an asset.

        If your partner already had permissions on the asset, they will be overriden with the new permissions you assign to them.

        To learn more about permission levels, visit https://help.pinterest.com/en/business/article/business-manager-overview


        Note: Not all listed permissions are applicable to each asset type. For example, PROFILE_PUBLISHER would not be

        applicable to an asset of type AD_ACCOUNT. The permission level PROFILE_PUBLISHER is only available to an asset of

        the type PROFILE.'
      operationId: update_partner_asset_access_handler_impl
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
    delete:
      summary: Delete partner access to asset
      description: 'Terminate multiple partners'' access to an asset. If

        - partner_type=INTERNAL: You will terminate a partner''s asset access to your business assets.

        - partner_type=EXTERNAL: You will terminate your own access to your partner''s business assets.'
      operationId: delete_partner_asset_access_handler_impl
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
  /businesses/{business_id}/partners/{partner_id}/assets:
    get:
      summary: Get assets assigned to a partner or assets assigned by a partner
      description: 'Can be used to get the business assets your partner has granted you access to or the business assets you have

        granted your partner access to. If you specify:

        - partner_type=INTERNAL, you will retrieve your business assets that the partner has access to.

        - partner_type=EXTERNAL, you will retrieve the partner''s business assets that the partner has granted you access to.'
      operationId: business_partner_asset_access/get
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Business
  /businesses/{business_id}/partners:
    get:
      summary: Get business partners
      description: "Get all partners of the specified business.\n\nIf the assets_summary=TRUE and:\n- partner_type=INTERNAL, the business assets returned are your business assets the partner has access to.\n- partner_type=EXTERNAL, the business assets returned are your partner's business assets the partner has granted you\n  access to."
      operationId: get/business_partners
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Business
    delete:
      summary: Terminate business partnerships
      description: 'Terminate partnerships between the specified partners and your business.

        Note: You may only batch terminate partners of the same partner type.'
      operationId: delete_business_partners
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
  /integrations/commerce/{external_business_id}:
    get:
      summary: Get commerce integration
      description: 'Get commerce integration metadata associated with the given external business ID.

        Note: If you''re interested in joining the beta, please reach out to your Pinterest account manager.'
      operationId: integrations_commerce/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Business
    patch:
      summary: Update commerce integration
      description: 'Update commerce integration metadata for the given external business ID.

        Note: If you''re interested in joining the beta, please reach out to your Pinterest account manager.'
      operationId: integrations_commerce/patch
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
    delete:
      summary: Delete commerce integration
      description: 'Delete commerce integration metadata for the given external business ID.

        Note: If you''re interested in joining the beta, please reach out to your Pinterest account manager.'
      operationId: integrations_commerce/del
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Business
components:
  securitySchemes:
    pinterest_oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.pinterest.com/oauth/
          tokenUrl: https://api.pinterest.com/v5/oauth/token
          scopes:
            ads:read: See all of your advertising data, including ads, ad groups, campaigns etc.
            ads:write: Create, update, or delete ads, ad groups, campaigns etc.
            billing:read: See all of your billing data, billing profile, etc.
            billing:write: Create, update, or delete billing data, billing profiles, etc.
            biz_access:read: See business access data
            biz_access:write: Create, update, or delete business access data
            boards:read: See your public boards, including group boards you join
            boards:read_secret: See your secret boards
            boards:write: Create, update, or delete your public boards
            boards:write_secret: Create, update, or delete your secret boards
            catalogs:read: See all of your catalogs data
            catalogs:write: Create, update, or delete your catalogs data
            pins:read: See your public Pins
            pins:read_secret: See your secret Pins
            pins:write: Create, update, or delete your public Pins
            pins:write_secret: Create, update, or delete your secret Pins
            user_accounts:read: See your user accounts and followers
            user_accounts:write: Update your user accounts and followers
    conversion_token:
      type: http
      scheme: bearer
      description: This security scheme only applies to the conversion events endpoint (POST /ad_accounts/{ad_account_id}/events). This endpoint requires a bearer token generated via Ads Manager (ads.pinterest.com).
    basic:
      type: http
      scheme: basic
x-tagGroups:
- name: Pin and Boards
  tags:
  - pins
  - boards
  - media
  - aggregated_comments
  - aggregated_pin_data
  - user_account
- name: Campaign Management
  tags:
  - ad_accounts
  - campaigns
  - ad_groups
  - ads
  - product_group_promotions
  - bulk
- name: Targeting
  tags:
  - audiences
  - customer_lists
  - keywords
  - targeting_template
  - audience_insights
  - audience_sharing
- name: Ad Formats
  tags:
  - lead_forms
  - lead_ads
  - leads_export
- name: Billing
  tags:
  - billing
  - order_lines
  - terms_of_service
- name: Business Access
  tags:
  - business_access_assets
  - business_access_invite
  - business_access_relationships
- name: Conversions
  tags:
  - conversion_events
  - conversion_tags
- name: Others
  tags:
  - integrations
  - oauth
  - resources
  - search
  - terms
- name: Shopping
  tags:
  - catalogs
- name: Deprecated
  tags:
  - product_groups
