openapi: 3.0.3
info:
  version: 5.13.0
  title: Pinterest Ad API
  description: This is the description of your API.
  contact:
    name: Pinterest, Inc.
    url: https://developers.pinterest.com/
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://developers.pinterest.com/terms/
servers:
- url: https://api.pinterest.com/v5
tags:
- name: Ad
paths:
  /ad_accounts:
    get:
      summary: List ad accounts
      description: 'Get a list of the ad_accounts that the "operation user_account" has access to.

        - This includes ad_accounts they own and ad_accounts that are owned by others who have granted them <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>.'
      tags:
      - Ad
      operationId: ad_accounts/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
    post:
      summary: Create ad account
      description: 'Create a new ad account. Different ad accounts can support different currencies, payment methods, etc.

        An ad account is needed to create campaigns, ad groups, and ads; other accounts (your employees or partners) can be assigned business access and appropriate roles to access an ad account. <p/>

        You can set up up to 50 ad accounts per user. (The user must have a business account to create an ad account.) <p/>

        For more, see <a class="reference external" href="https://help.pinterest.com/en/business/article/create-an-advertiser-account">Create an advertiser account</a>.'
      tags:
      - Ad
      operationId: ad_accounts/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
  /ad_accounts/{ad_account_id}:
    get:
      summary: Get ad account
      description: Get an ad account
      operationId: ad_accounts/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ad_groups:
    get:
      summary: List ad groups
      description: 'List ad groups based on provided campaign IDs or ad group IDs.(campaign_ids or ad_group_ids). <p/>

        <strong>Note:</strong><p/>

        Provide only campaign_id or ad_group_id. Do not provide both.'
      operationId: ad_groups/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
    post:
      summary: Create ad groups
      description: "Create multiple new ad groups. All ads in a given ad group will have the same budget, bid, run dates, targeting, and placement (search, browse, other). For more information, <a href=\"https://help.pinterest.com/en/business/article/campaign-structure\" target=\"_blank\"> click here</a>.</p>\n<strong>Note:</strong>\n- 'bid_in_micro_currency' and 'budget_in_micro_currency' should be expressed in microcurrency amounts based on the currency field set in the advertiser's profile.<p[...]"
      operationId: ad_groups/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - Ad
    patch:
      summary: Update ad groups
      description: Update multiple existing ad groups.
      operationId: ad_groups/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ad_groups/analytics:
    get:
      summary: Get ad group analytics
      description: 'Get analytics for the specified ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.

        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.

        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.'
      operationId: ad_groups/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ad_groups/targeting_analytics:
    get:
      summary: Get targeting analytics for ad groups
      description: 'Get targeting analytics for one or more ad groups.

        For the requested ad group(s) and metrics, the response will include the requested metric information

        (e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. "age_bucket") for applicable values (e.g. "45-49"). <p/>

        - The token''s user_account must either be the Owner of the specified ad account, or have one

        of the necessary roles granted to them via

        <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.

        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.

        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.'
      operationId: ad_groups_targeting_analytics/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ad_groups/audience_sizing:
    post:
      summary: Get audience sizing
      description: "Get potential audience size for an ad group with given targeting criteria. \nPotential audience size estimates the number of people you may be able to reach per month with your campaign. \nIt is based on historical advertising data and the targeting criteria you select.\nIt does not guarantee results or take into account factors such as bid, budget, schedule, seasonality or product experiments."
      operationId: ad_groups/audience_sizing
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ad_groups/{ad_group_id}:
    get:
      summary: Get ad group
      description: 'Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will

        contain additional information from the Ad Review process.

        For more information about our policies and rejection reasons see the <a href="https://www.pinterest.com/_/_/policy/advertising-guidelines/"

        target="_blank">Pinterest advertising standards</a>.'
      operationId: ad_groups/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ad_previews:
    post:
      summary: Create ad preview with pin or image
      description: 'Create an ad preview given an ad account ID and either an existing organic pin ID or the URL for an image to be used to create the Pin and the ad. <p/>

        If you are creating a preview from an existing Pin, that Pin must be promotable: that is, it must have a clickthrough link and meet other requirements. (See <a href="https://help.pinterest.com/en/business/article/promoted-pins-overview" target="_blank">Ads Overview</a>.) <p/>

        You can view the returned preview URL on a webpage or iframe for 7 days, after which the URL expires. Collection ads are not currently supported ad preview.'
      tags:
      - Ad
      operationId: ad_previews/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
  /ad_accounts/{ad_account_id}/ads:
    get:
      summary: List ads
      description: "List ads that meet the filters provided:\n  - Listed campaign ids or ad group ids or ad ids\n  - Listed entity statuses <p/>\nIf no filter is provided, all ads in the ad account are returned. <p/>\n<strong>Note:</strong><p/>\nProvide only campaign_id or ad_group_id or ad_id. Do not provide more than one type. <p/>\nReview status is provided for each ad; if review_status is REJECTED, the rejected_reasons field will contain additional information.\nFor more, see <a href=\"https[...]"
      operationId: ads/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
    post:
      description: Create multiple new ads. Request must contain ad_group_id, creative_type, and the source Pin pin_id.
      operationId: ads/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      summary: Create ads
      tags:
      - Ad
    patch:
      description: Update multiple existing ads
      operationId: ads/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      summary: Update ads
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ads/analytics:
    get:
      summary: Get ad analytics
      description: 'Get analytics for the specified ads in the specified <code>ad_account_id</code>, filtered by the specified options.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.

        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.

        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.'
      operationId: ads/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ads_credit/discounts:
    get:
      summary: Get ads credit discounts
      description: 'Returns the list of discounts applied to the account.


        <strong>This endpoint might not be available to all apps. <a href=''/docs/new/about-beta-access/''>Learn more</a>.</strong>'
      operationId: ads_credits_discounts/get
      security:
      - pinterest_oauth2:
        - ads:read
        - billing:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ads_credit/redeem:
    post:
      summary: Redeem ad credits
      description: 'Redeem ads credit on behalf of the ad account id and apply it towards billing.


        <strong>This endpoint might not be available to all apps. <a href=''/docs/new/about-beta-access/''>Learn more</a>.</strong>'
      tags:
      - Ad
      operationId: ads_credit/redeem
      security:
      - pinterest_oauth2:
        - ads:write
        - billing:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
  /ad_accounts/{ad_account_id}/ads/targeting_analytics:
    get:
      summary: Get targeting analytics for ads
      description: 'Get targeting analytics for one or more ads. For the requested ad(s) and metrics,

        the response will include the requested metric information (e.g. SPEND_IN_DOLLAR) for the requested target type

        (e.g. "age_bucket") for applicable values (e.g. "45-49"). <p/>

        - The token''s user_account must either be the Owner of the specified ad account, or have one

        of the necessary roles granted to them via

        <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.

        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.

        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.'
      operationId: ad_targeting_analytics/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ads/{ad_id}:
    get:
      summary: Get ad
      description: 'Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will

        contain additional information from the Ad Review process.

        For more information about our policies and rejection reasons see the <a href="https://www.pinterest.com/_/_/policy/advertising-guidelines/"

        target="_blank">Pinterest advertising standards</a>.'
      operationId: ads/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/analytics:
    get:
      summary: Get ad account analytics
      description: 'Get analytics for the specified <code>ad_account_id</code>, filtered by the specified options.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.

        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.

        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time.'
      operationId: ad_account/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/audience_insights:
    get:
      summary: Get audience insights
      description: 'Get Audience Insights for an ad account. The response will return insights for 3 types of audiences: the

        ad account''s engaged audience on Pinterest, the ad account''s total audience on Pinterest and Pinterest''s

        total audience.<p/>

        <a href="https://help.pinterest.com/en/business/article/audience-insights" target="_blank">Learn more about Audience Insights</a>.'
      operationId: audience_insights/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/audiences:
    get:
      summary: List audiences
      description: Get list of audiences for the ad account.
      operationId: audiences/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
    post:
      description: 'Create an audience you can use in targeting for specific ad groups. Targeting combines customer information with

        the ways users interact with Pinterest to help you reach specific groups of users; you can include or exclude

        specific audience_ids when you create an ad group. <p/>

        For more, see <a class="reference external" href="https://help.pinterest.com/en/business/article/audience-targeting" target="_blank">Audience targeting</a>.'
      operationId: audiences/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Create audience
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/audiences/{audience_id}:
    get:
      summary: Get audience
      description: Get a specific audience given the audience ID.
      operationId: audiences/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
    patch:
      summary: Update audience
      description: Update (edit or remove) an existing targeting audience.
      operationId: audiences/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/audiences/custom:
    post:
      summary: Create custom audience
      description: Create a custom audience and find the audiences you want your ads to reach.
      operationId: audiences/create_custom
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/bid_floor:
    post:
      description: "List bid floors for your campaign configuration. Bid floors are given in microcurrency values based on the currency in the bid floor specification. <p/>\n<p>Microcurrency is used to track very small transactions, based on the currency set in the advertisers profile.</p>\n<p>A microcurrency unit is 10^(-6) of the standard unit of currency selected in the advertiser s profile.</p>\n<p><strong>Equivalency equations</strong>, using dollars as an example currency:</p>\n<ul>\n  <li[...]"
      operationId: ad_groups_bid_floor/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      summary: Get bid floors
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/billing_profiles:
    get:
      summary: Get billing profiles
      description: 'Get billing profiles in the advertiser account.


        <strong>This endpoint might not be available to all apps. <a href=''/docs/new/about-beta-access/''>Learn more</a>.</strong>'
      operationId: billing_profiles/get
      security:
      - pinterest_oauth2:
        - ads:read
        - billing:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/bulk/download:
    post:
      summary: Get advertiser entities in bulk
      description: 'Create an asynchronous report that may include information on campaigns, ad groups, product groups, ads,

        and/or keywords; can filter by campaigns. Though the entities may be active, archived, or paused,

        only active entities will return data.'
      operationId: bulk_download/create
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/bulk/upsert:
    post:
      description: 'Either create or update any combination of campaigns, ad groups, product groups, ads, or keywords.

        Note that this request will be processed asynchronously; the response will include a <code>request_id</code>

        that can be used to obtain the status of the request.'
      operationId: bulk_upsert/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Create/update ad entities in bulk
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/bulk/{bulk_request_id}:
    get:
      description: 'Get the status of a bulk request by <code>request_id</code>, along with a download URL that will allow you to download the

        new or updated entity data (campaigns, ad groups, product groups, ads, or keywords).'
      operationId: bulk_request/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      summary: Download advertiser entities in bulk
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/campaigns:
    get:
      summary: List campaigns
      description: 'Get a list of the campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.'
      operationId: campaigns/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
    post:
      summary: Create campaigns
      description: "Create multiple new campaigns. Every campaign has its own campaign_id and houses one or more ad groups, which contain one or more ads.\nFor more, see <a href=\"https://help.pinterest.com/en/business/article/set-up-your-campaign/\">Set up your campaign</a>. <p/>\n<strong>Note:</strong>\n- The values for 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency amounts based on the currency field set in the advertiser's profile. (e.g. USD) <p/>\n<p>Microcurrency is used to t[...]"
      tags:
      - Ad
      operationId: campaigns/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
    patch:
      summary: Update campaigns
      description: "Update multiple ad campaigns based on campaign_ids. <p/>\n<strong>Note:</strong><p/>\n - <p>The values for 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency amounts based on the currency field set in the advertiser's profile. (e.g. USD) <p/>\n<p>Microcurrency is used to track very small transactions, based on the currency set in the advertisers profile.</p>\n<p>A microcurrency unit is 10^(-6) of the standard unit of currency selected in the advertiser s profile.</p[...]"
      tags:
      - Ad
      operationId: campaigns/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
  /ad_accounts/{ad_account_id}/campaigns/analytics:
    get:
      summary: Get campaign analytics
      description: 'Get analytics for the specified campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.

        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.

        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.'
      operationId: campaigns/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/campaigns/targeting_analytics:
    get:
      summary: Get targeting analytics for campaigns
      description: 'Get targeting analytics for one or more campaigns.

        For the requested account and metrics, the response will include the requested metric information

        (e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. "age_bucket") for applicable values (e.g. "45-49"). <p/>

        - The token''s user_account must either be the Owner of the specified ad account, or have one

        of the necessary roles granted to them via

        <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.

        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.

        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.'
      operationId: campaign_targeting_analytics/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/campaigns/{campaign_id}:
    get:
      summary: Get campaign
      description: Get a specific campaign given the campaign ID.
      operationId: campaigns/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/conversion_tags:
    get:
      summary: Get conversion tags
      description: List conversion tags associated with an ad account.
      operationId: conversion_tags/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - Ad
      x-sandbox: disabled
    post:
      x-sandbox: disabled
      summary: Create conversion tag
      description: 'Create a conversion tag, also known as <a href="https://help.pinterest.com/en/business/article/set-up-the-pinterest-tag" target="_blank">Pinterest tag</a>, with the option to enable enhanced match.<p/>

        The Pinterest Tag tracks actions people take on the ad account s website after they view the ad account''s ad on Pinterest. The advertiser needs to customize this tag to track conversions.<p/>

        For more information, see:<p/>

        <a class="reference external" href="https://help.pinterest.com/en/business/article/set-up-the-pinterest-tag">Set up the Pinterest tag</a><p/>

        <a class="reference external" href="https://developers.pinterest.com/docs/conversions/pinterest-tag/">Pinterest Tag</a><p/>

        <a class="reference external" href="https://developers.pinterest.com/docs/conversions/enhanced-match/">Enhanced match</a>'
      operationId: conversion_tags/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/conversion_tags/ocpm_eligible:
    get:
      summary: Get Ocpm eligible conversion tags
      description: Get Ocpm eligible conversion tag events for an ad account.
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      operationId: ocpm_eligible_conversion_tags/get
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/conversion_tags/page_visit:
    get:
      summary: Get page visit conversion tags
      description: Get all page visit conversion tag events for an ad account.
      operationId: page_visit_conversion_tags/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/conversion_tags/{conversion_tag_id}:
    get:
      x-sandbox: disabled
      summary: Get conversion tag
      description: Get information about an existing conversion tag.
      operationId: conversion_tags/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/customer_lists:
    post:
      description: "<p>Create a customer list from your records(hashed or plain-text email addresses, or hashed MAIDs or IDFAs).</p>\n<p>A customer list is one of the four types of Pinterest audiences: for more information, see <a href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>\nor the <a href=\"/docs/ads/targeting/#Audiences\" target=\"_blank\">Audiences</a> section of the ads management guide.<p/>\n <p><b>Please review our <u>[...]"
      operationId: customer_lists/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Create customer lists
      tags:
      - Ad
    get:
      description: "<p>Get a set of customer lists including id and name based on the filters provided.</p>\n<p>(Customer lists are a type of audience.) For more information, see\n<a href=\"https://help.pinterest.com/en/business/article/audience-targeting\" target=\"_blank\">Audience targeting</a>\n or the <a href=\"/docs/ads/targeting/#Audiences\" target=\"_blank\">Audiences</a>\nsection of the ads management guide.</p>"
      operationId: customer_lists/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      summary: Get customer lists
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/customer_lists/{customer_list_id}:
    get:
      summary: Get customer list
      description: Gets a specific customer list given the customer list ID.
      operationId: customer_lists/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
    patch:
      description: "<p>Append or remove records to/from an existing customer list. (A customer list is one of the four types of Pinterest audiences.)</p>\n<p>When you add records to an existing customer list, the system scans the additions for existing Pinterest\naccounts; those are the records that will be added to your CUSTOMER_LIST audience. Your original list of records\n to add will be deleted when the matching process is complete.</p>\n<p>For more information, see <a href=\"https://help.pi[...]"
      operationId: customer_lists/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Update customer list
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/events:
    post:
      summary: Send conversions
      description: 'The Pinterest API offers advertisers a way to send Pinterest their conversion information (including web conversions, in-app conversions, or even offline conversions) based on their <code>ad_account_id</code>. The request body should be a JSON object.

        - This endpoint requires an <code>access_token</code> be generated through Ads Manager. Review the <a href="/docs/conversions/conversions/">Conversions Guide</a> for more details.

        - The token''s <code>user_account</code> must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Audience, Campaign. (Note that the token can be used across multiple ad accounts under an user ID.)

        - This endpoint has a rate limit of 5,000 calls per minute per ad account.

        - If the merchant is submitting this information using both Pinterest conversion tags and the Pinterest API, Pinterest will remove duplicate information before reporting. (Note that events that took place offline cannot be deduplicated.)'
      operationId: events/create
      tags:
      - Ad
      security:
      - pinterest_oauth2:
        - ads:write
      - conversion_token: []
      x-ratelimit-category: ads_conversions
      x-sandbox: disabled
  /ad_accounts/{ad_account_id}/insights/audiences:
    get:
      summary: Get audience insights scope and type
      description: Get the scope and type of available audiences, which along with a date, is an audience that has recently had an interaction (referred to here as a type) on pins. Interacted pins can belong to at least the most common **partner** or **Pinterest** scopes. This means that user interactions made on advertiser or partner pins will have the **partner** scope. You can also have user interactions performed in general on Pinterest with the **Pinterest** scope. In that case, you can the[...]
      operationId: audience_insights_scope_and_type/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/keywords:
    get:
      summary: Get keywords
      description: '<p>Get a list of keywords based on the filters provided. If no filter is provided, it will default to the ad_account_id filter, which means it will only return keywords that specifically have parent_id set to the ad_account_id. Note: Keywords can have ad_account_ids, campaign_ids, and ad_group_ids set as their parent_ids. Keywords created through Ads Manager will have their parent_id set to an ad_group_id, not ad_account_id.</p>

        <p>For more information, see <a target="_blank" href="https://help.pinterest.com/en/business/article/keyword-targeting">Keyword targeting</a>.</p>

        <p><b>Notes:</b></p> <ul style="list-style-type: square;"> <li>Advertisers and campaigns can only be assigned keywords with excluding (''_NEGATIVE'').</li> <li>All keyword match types are available for ad groups.</li> </ul> <p>For more information on match types, see <a target="_blank" href="/docs/ads/targeting/#Match%20type%20and%20targeting%20level">match type enums</a>.</p>

        <p><b>Returns:</b></p> <ul style="list-style-type: square;"> <li><p>A successful call returns an object containing an array of new keyword objects and an empty &quot;errors&quot; object array.</p></li> <li><p>An unsuccessful call returns an empty keywords array, and, instead, inserts the entire object with nulled/negated properties into the &quot;errors&quot; object array:</p> <pre class="last literal-block"> { "keywords": [], "errors": [ { "data": { "archived": null, "match_type": "EXAC[...]'
      operationId: keywords/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
    post:
      summary: Create keywords
      description: '<p>Create keywords for following entity types(advertiser, campaign, ad group or ad).</p> <p>For more information, see <a target="_blank" href="https://help.pinterest.com/en/business/article/keyword-targeting">Keyword targeting</a>.</p>

        <p><b>Notes:</b></p> <ul style="list-style-type: square;"> <li>Advertisers and campaigns can only be assigned keywords with excluding (''_NEGATIVE'').</li> <li>All keyword match types are available for ad groups.</li> </ul> <p>For more information on match types, see <a  target="_blank" href="/docs/ads/targeting/#Match%20type%20and%20targeting%20level">match type enums</a>.</p>

        <p><b>Returns:</b></p> <ul style="list-style-type: square;"> <li><p>A successful call returns an object containing an array of new keyword objects and an empty &quot;errors&quot; object array.</p></li> <li><p>An unsuccessful call returns an empty keywords array, and, instead, inserts the entire object with nulled/negated properties into the &quot;errors&quot; object array:</p> <pre class="last literal-block"> { "keywords": [], "errors": [ { "data": { "archived": null, "match_type": "EXAC[...]

        <p><b>Rate limit</b>: <a href="/docs/redoc/#tag/Rate-Limits">WRITE</a>.</p>'
      operationId: keywords/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - Ad
    patch:
      summary: Update keywords
      description: <p>Update one or more keywords' bid and archived fields.</p> <p>Archiving a keyword effectively deletes it - keywords no longer receive metrics and no longer visible within the parent entity's keywords list.</p>
      operationId: keywords/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/keywords/metrics:
    get:
      summary: Get country's keyword metrics
      description: 'See keyword metrics for a specified country, aggregated across all of Pinterest.

        (Definitions are available from the "Get delivery metrics definitions"

        <a href="/docs/api/v5/#operation/delivery_metrics/get">API endpoint</a>).'
      operationId: country_keywords_metrics/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/lead_forms:
    get:
      summary: Get lead forms
      description: '<strong>This feature is currently in beta and not available to all apps, if you''re interested in joining the beta, please reach out to your Pinterest account manager.</strong>


        Gets all Lead Forms associated with an ad account ID.


        For more, see <a class="reference external" href="https://help.pinterest.com/en/business/article/lead-ads">Lead ads</a>.'
      operationId: lead_forms/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/lead_forms/{lead_form_id}:
    get:
      summary: Get lead form by id
      description: '<strong>This feature is currently in beta and not available to all apps, if you''re interested in joining the beta, please reach out to your Pinterest account manager.</strong>


        Gets a lead form given it''s ID. It must also be associated with the provided ad account ID.


        For more, see <a class="reference external" href="https://help.pinterest.com/en/business/article/lead-ads">Lead ads</a>.'
      operationId: lead_form/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/lead_forms/{lead_form_id}/test:
    post:
      summary: Create lead form test data
      description: 'Create lead form test data based on the list of answers provided as part of the body.

        - List of answers should follow the questions creation order.


        <strong>This endpoint is currently in beta and not available to all apps. <a href=''/docs/new/about-beta-access/''>Learn more</a>.</strong>'
      operationId: lead_form_test/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/leads/subscriptions:
    post:
      summary: Create lead ads subscription
      description: "Create a lead ads webhook subscription.\nSubscriptions allow Pinterest to deliver lead data from Ads Manager directly to the subscriber. Subscriptions can exist for a specific lead form or at ad account level. \n- Only requests for the OWNER or ADMIN of the ad_account will be allowed.\n- Advertisers can set up multiple integrations using ad_account_id + lead_form_id but only one integration per unique records.\n- For data security, egress lead data is encrypted with AES-256-G[...]"
      tags:
      - Ad
      operationId: ad_accounts_subscriptions/post
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
    get:
      summary: Get lead ads subscriptions
      description: 'Get the advertiser''s list of lead ads subscriptions.

        - Only requests for the OWNER or ADMIN of the ad_account will be allowed.


        <strong>This endpoint is currently in beta and not available to all apps. <a href=''/docs/new/about-beta-access/''>Learn more</a>.</strong>'
      operationId: ad_accounts_subscriptions/get_list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/leads/subscriptions/{subscription_id}:
    get:
      summary: Get lead ads subscription
      description: 'Get a specific lead ads subscription record.

        - Only requests for the OWNER or ADMIN of the ad_account will be allowed.


        <strong>This endpoint is currently in beta and not available to all apps. <a href=''/docs/new/about-beta-access/''>Learn more</a>.</strong>'
      operationId: ad_accounts_subscriptions/get_by_id
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
    delete:
      summary: Delete lead ads subscription
      description: 'Delete an existing lead ads webhook subscription by ID.

        - Only requests for the OWNER or ADMIN of the ad_account will be allowed.


        <strong>This endpoint is currently in beta and not available to all apps. <a href=''/docs/new/about-beta-access/''>Learn more</a>.</strong>'
      operationId: ad_accounts_subscriptions/del_by_id
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/mmm_reports:
    get:
      summary: Get advertiser Marketing Mix Modeling (MMM) report.
      description: 'Get an mmm report for an ad account. This returns a URL to an mmm metrics report given a token returned from the

        create mmm report endpoint.'
      operationId: analytics/get_mmm_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
    post:
      summary: Create a request for a Marketing Mix Modeling (MMM) report
      description: 'This creates an asynchronous mmm report based on the given request. It returns a token that you can use to download

        the report when it is ready. NOTE: An additional limit of 5 queries per minute per advertiser applies to this endpoint while it''s in beta release.'
      operationId: analytics/create_mmm_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/order_lines:
    get:
      summary: Get order lines
      description: List existing order lines associated with an ad account.
      operationId: order_lines/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/order_lines/{order_line_id}:
    get:
      summary: Get order line
      description: Get a specific existing order line associated with an ad account.
      operationId: order_lines/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/product_group_promotions:
    post:
      description: Add one or more product groups from your catalog to an existing ad group. (Product groups added to an ad group are a 'product group promotion.')
      operationId: product_group_promotions/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Create product group promotions
      tags:
      - Ad
    patch:
      description: Update multiple existing Product Group Promotions (by product_group_id)
      operationId: product_group_promotions/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Update product group promotions
      tags:
      - Ad
    get:
      description: 'List existing product group promotions associated with an ad account.


        Include either ad_group_id or product_group_promotion_ids in your request.


        <b>Note:</b> ad_group_ids and product_group_promotion_ids are mutually exclusive parameters.

        Only provide one. If multiple options are provided, product_group_promotion_ids takes precedence over ad_group_ids. If none are provided, the endpoint returns an error.'
      operationId: product_group_promotions/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      summary: Get product group promotions
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/product_group_promotions/{product_group_promotion_id}:
    get:
      description: Get a product group promotion by id
      operationId: product_group_promotions/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      summary: Get a product group promotion by id
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/product_groups/analytics:
    get:
      summary: Get product group analytics
      description: 'Get analytics for the specified product groups in the specified <code>ad_account_id</code>, filtered by the specified options.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.

        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.

        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.'
      operationId: product_groups/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/product_groups/catalogs:
    get:
      deprecated: true
      description: This endpoint is completely deprecated. Please use <a href='/docs/api/v5/#operation/catalogs_product_groups/list'>List product groups</a> from Catalogs API instead.
      operationId: ad_accounts_catalogs_product_groups/list
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Get catalog product groups
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/reports:
    get:
      summary: Get the account analytics report created by the async call
      description: 'This returns a URL to an analytics report given a token returned from the post request report creation call. You can use the URL to download the report. The link is valid for five minutes and the report is valid for one hour.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.'
      operationId: analytics/get_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: disabled
      tags:
      - Ad
    post:
      summary: Create async request for an account analytics report
      description: 'This returns a token that you can use to download the report when it is ready. Note that this endpoint requires the parameters to be passed as JSON-formatted in the request body. This endpoint does not support URL query parameters.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.

        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 914 days before the current date in UTC time and the max time range supported is 186 days.

        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.

        - If level is PRODUCT_ITEM, the furthest back you can are allowed to pull data is 92 days before the current date in UTC time and the max time range supported is 31 days.

        - If level is PRODUCT_ITEM, ad_ids and ad_statuses parameters are not allowed. Any columns related to pin promotion and ad is not allowed either.'
      operationId: analytics/create_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/sandbox:
    delete:
      summary: Delete ads data for ad account in API Sandbox
      description: "Delete an ad account and all the ads data associated with that account. \nA string message is returned indicating the status of the delete operation.\n\nNote: This endpoint is only allowed in the Pinterest API Sandbox (https://api-sandbox.pinterest.com/v5). \nGo to https://developers.pinterest.com/docs/dev-tools/sandbox/ for more information."
      operationId: sandbox/delete
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ssio/accounts:
    get:
      summary: Get Salesforce account details including bill-to information.
      description: 'Get Salesforce account details including bill-to information to be used in insertion orders process for <code>ad_account_id</code>.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.'
      operationId: ssio_accounts/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ssio/insertion_orders:
    post:
      summary: Create insertion order through SSIO.
      description: 'Create insertion order through SSIO for <code>ad_account_id</code>.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.'
      operationId: ssio_insertion_order/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - Ad
    patch:
      summary: Edit insertion order through SSIO.
      description: 'Edit insertion order through SSIO for <code>ad_account_id</code>.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.'
      operationId: ssio_insertion_order/edit
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ssio/insertion_orders/status:
    get:
      summary: Get insertion order status by ad account id.
      description: 'Get insertion order status for account id <code>ad_account_id</code>.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.'
      operationId: ssio_insertion_orders_status/get_by_ad_account
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ssio/insertion_orders/{pin_order_id}/status:
    get:
      summary: Get insertion order status by pin order id.
      description: 'Get insertion order status for pin order id <code>pin_order_id</code>.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.'
      operationId: ssio_insertion_orders_status/get_by_pin_order_id
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/ssio/order_lines:
    get:
      summary: Get Salesforce order lines by ad account id.
      description: 'Get Salesforce order lines for account id <code>ad_account_id</code>.

        - The token''s user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.'
      operationId: ssio_order_lines/get_by_ad_account
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/targeting_analytics:
    get:
      summary: Get targeting analytics for an ad account
      description: 'Get targeting analytics for an ad account.

        For the requested account and metrics, the response will include the requested metric information

        (e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. "age_bucket") for applicable values (e.g. "45-49"). <p/>

        - The token''s user_account must either be the Owner of the specified ad account, or have one

        of the necessary roles granted to them via

        <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.

        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.

        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.'
      operationId: ad_account_targeting_analytics/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/targeting_templates:
    get:
      summary: List targeting templates
      description: Get a list of the targeting templates in the specified <code>ad_account_id</code>
      operationId: targeting_template/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - Ad
    post:
      summary: Create targeting templates
      description: "<p>Targeting templates allow advertisers to save a set of targeting details including audience lists,\n keywords & interest, demographics, and placements to use more than once during the campaign creation process.</p>\n <p>Templates can be used to build out basic targeting criteria that you plan to use across campaigns and to reuse\n  performance targeting from prior campaigns for new campaigns.</p>"
      operationId: targeting_template/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - Ad
    patch:
      summary: Update targeting templates
      description: <p>Update the targeting template given advertiser ID and targeting template ID</p>
      operationId: targeting_template/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/templates:
    get:
      summary: List templates
      description: Gets all Templates associated with an ad account ID.
      operationId: templates/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/templates/{template_id}/reports:
    post:
      summary: Create async request for an analytics report using a template
      description: 'This takes a template ID and an optional custom timeframe and constructs an asynchronous report based on the

        template. It returns a token that you can use to download the report when it is ready.'
      operationId: analytics/create_template_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: disabled
      tags:
      - Ad
  /ad_accounts/{ad_account_id}/terms_of_service:
    get:
      description: Get the text of the terms of service and see whether the advertiser has accepted the terms of service.
      operationId: terms_of_service/get
      x-sandbox: enabled
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      summary: Get terms of service
      tags:
      - Ad
  /resources/ad_account_countries:
    get:
      summary: Get ad accounts countries
      description: Get Ad Accounts countries
      operationId: ad_account_countries/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - Ad
components:
  securitySchemes:
    pinterest_oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.pinterest.com/oauth/
          tokenUrl: https://api.pinterest.com/v5/oauth/token
          scopes:
            ads:read: See all of your advertising data, including ads, ad groups, campaigns etc.
            ads:write: Create, update, or delete ads, ad groups, campaigns etc.
            billing:read: See all of your billing data, billing profile, etc.
            billing:write: Create, update, or delete billing data, billing profiles, etc.
            biz_access:read: See business access data
            biz_access:write: Create, update, or delete business access data
            boards:read: See your public boards, including group boards you join
            boards:read_secret: See your secret boards
            boards:write: Create, update, or delete your public boards
            boards:write_secret: Create, update, or delete your secret boards
            catalogs:read: See all of your catalogs data
            catalogs:write: Create, update, or delete your catalogs data
            pins:read: See your public Pins
            pins:read_secret: See your secret Pins
            pins:write: Create, update, or delete your public Pins
            pins:write_secret: Create, update, or delete your secret Pins
            user_accounts:read: See your user accounts and followers
            user_accounts:write: Update your user accounts and followers
    conversion_token:
      type: http
      scheme: bearer
      description: This security scheme only applies to the conversion events endpoint (POST /ad_accounts/{ad_account_id}/events). This endpoint requires a bearer token generated via Ads Manager (ads.pinterest.com).
    basic:
      type: http
      scheme: basic
x-tagGroups:
- name: Pin and Boards
  tags:
  - pins
  - boards
  - media
  - aggregated_comments
  - aggregated_pin_data
  - user_account
- name: Campaign Management
  tags:
  - ad_accounts
  - campaigns
  - ad_groups
  - ads
  - product_group_promotions
  - bulk
- name: Targeting
  tags:
  - audiences
  - customer_lists
  - keywords
  - targeting_template
  - audience_insights
  - audience_sharing
- name: Ad Formats
  tags:
  - lead_forms
  - lead_ads
  - leads_export
- name: Billing
  tags:
  - billing
  - order_lines
  - terms_of_service
- name: Business Access
  tags:
  - business_access_assets
  - business_access_invite
  - business_access_relationships
- name: Conversions
  tags:
  - conversion_events
  - conversion_tags
- name: Others
  tags:
  - integrations
  - oauth
  - resources
  - search
  - terms
- name: Shopping
  tags:
  - catalogs
- name: Deprecated
  tags:
  - product_groups
